# Generated by Django 4.2.3 on 2023-07-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_registration_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
