# Generated by Django 4.2.3 on 2023-07-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
