# Generated by Django 4.2.3 on 2023-07-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_medicine_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='academic_degree',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='free_time',
            new_name='degree',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_image',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='medicine_image',
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicines/'),
        ),
    ]
