# Generated by Django 4.2.3 on 2023-07-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='education',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='summary',
        ),
    ]
