# Generated by Django 4.2.3 on 2023-07-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0008_remove_doctor_education_remove_doctor_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
    ]
