# Generated by Django 4.2.3 on 2023-07-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0012_remove_doctor_availability_remove_doctor_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.CharField(default='Monday to Friday', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(default='MD', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='departments.department'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(default='123456789', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='summary',
            field=models.TextField(default='No summary available'),
        ),
    ]
