# Generated by Django 4.2.3 on 2023-07-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0013_doctor_availability_doctor_degree_doctor_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='education',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.doctor')),
            ],
        ),
    ]
